name: Build and Deploy
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Install and Build
              run: |
                  npm install
                  npm run build
            - name: Deploy Build Files
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              run: |
                  cd build
                  git config --global user.email "gkswlgp456@gmail.com"
                  git config --global user.name "jejecrunch"
                  git init
                  git add -A
                  git commit -m "deploy: deploy contents"
                  git push -f https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages